name: pygranso_cuda_env
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - argon2-cffi=21.1.0=py39h3811e60_2
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd8ed1ab_0
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.10.8=ha878542_0
  - cffi=1.15.0=py39h4bc2ebd_0
  - cudatoolkit=11.1.1=h6406543_9
  - debugpy=1.5.1=py39he80948d_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - importlib-metadata=4.8.2=py39hf3d152e_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - ipykernel=6.5.0=py39hef51801_1
  - ipython=7.30.0=py39hf3d152e_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.1=py39hf3d152e_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=4.2.1=pyhd8ed1ab_0
  - jupyter_client=7.1.0=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py39hf3d152e_1
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libffi=3.4.2=h9c3ff4c_4
  - libgcc-ng=11.2.0=h1d223b6_9
  - libgfortran-ng=7.5.0=h14aa051_19
  - libgfortran4=7.5.0=h14aa051_19
  - libiconv=1.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=he4da1e4_9
  - libtiff=4.2.0=h85742a9_0
  - libuv=1.42.0=h7f98852_0
  - libwebp-base=1.2.1=h7f98852_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.0.1=py39h3811e60_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py39h3811e60_1005
  - mkl=2021.3.0=h726a3e6_557
  - mkl-service=2.4.0=py39h3811e60_0
  - mkl_fft=1.3.0=py39h42c9631_2
  - mkl_random=1.2.2=py39hde0f152_0
  - nbclient=0.5.9=pyhd8ed1ab_0
  - nbconvert=6.3.0=py39hf3d152e_1
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - ninja=1.10.2=h4bd325d_1
  - notebook=6.4.6=pyha770c72_0
  - numpy=1.20.3=py39hf144106_0
  - numpy-base=1.20.3=py39h74d4b33_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.0=h7f98852_2
  - osqp=0.6.2=py39hde0f152_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandoc=2.16.2=h7f98852_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.1=py39h2c7a002_0
  - pip=21.2.4=pyhd8ed1ab_0
  - prometheus_client=0.12.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.22=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - pyrsistent=0.18.0=py39h3811e60_0
  - python=3.9.7=hf930737_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.9.0=py3.9_cuda11.1_cudnn8.0.5_0
  - pyzmq=22.3.0=py39h37b5a0c_1
  - qdldl-python=0.1.5=py39hde0f152_1
  - readline=8.1=h46c0cb4_0
  - scipy=1.7.1=py39h292c36d_2
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.0.4=py39hf3d152e_2
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h9cd32fc_2
  - tbb=2021.3.0=h4bd325d_0
  - terminado=0.12.1=py39hf3d152e_1
  - testpath=0.5.0=pyhd8ed1ab_0
  - tk=8.6.11=h27826a3_1
  - torchaudio=0.9.0=py39
  - torchvision=0.10.0=py39_cu111
  - tornado=6.1=py39h3811e60_2
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyha770c72_0
  - tzdata=2021a=he74cb21_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=h516909a_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1011
  - zstd=1.4.9=ha95c52a_0
prefix: /home/buyun/anaconda3/envs/pygranso_cuda_env
